/*!
 *  \author    Mariusz Wiśniewski
 *  \date      3/19/20
 */

#ifndef DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H
#define DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H

#define NUMBER_OF_PHILOSOPHERS 5
#define THINKING_TIME 200
#define EATING_TIME 300
#define FEAST_TIME 5

#endif //DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H
