/*!
 *  \author    Mariusz Wiśniewski
 *  \date      3/19/20
 */

#ifndef DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H
#define DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H

#define NUMBER_OF_PHILOSOPHERS 4
#define THINKING_TIME 500
#define EATING_TIME 250
#define FEAST_TIME 5

#endif //DINING_PHILOSOPHERS_PROBLEM_PARAMETERS_H
